### PR TITLE
Twitter feed

### PR DESCRIPTION
**Pull request by purplecones**
@alimgafar @alanning see preview of twitter feed below

meteorcampnyctwitterfeed

Still want to add a fade in/out effect but having a hard time figuring out the React CSS Transition Groups. I'll ask for help tomorrow, maybe someone can help improve it.

### CODE REVIEW

**Comment by alimgafar** [comment]
Mirza,

This is awesome. If we do this, could we make sure they stick around for about 3 seconds? It’s hard to read if they’re flashing by.

**Comment by purplecones** [comment]
It's 8 seconds currently.

## 

Mirza Joldic

**Comment by alimgafar** [comment]
Okay. Make it 15. It's too fast to read comfortably.

**Comment by purplecones** [comment]
@alimgafar done

**Pull request merged**
